In [1]:
import numpy as np

In [2]:
# pip install numpy

In [3]:
my_list = [10,20,30,40]

In [4]:
type(my_list) 

list

In [5]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
type(my_numpy_array)

numpy.ndarray

In [9]:
my_numpy_array.max()

np.int64(40)

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.random.random(5)

array([0.38399335, 0.87825033, 0.51121422, 0.34074164, 0.80612963])

In [14]:
# burada numpy rastgele degerler urettik 

In [15]:
#  ARRAY ARITMATIK

In [17]:
my_list1 = [1,2]

In [19]:
my_list2 = [2,3]

In [21]:
my_list1 + my_list2 #  yan yana koyma islemi yapiyoruz

[1, 2, 2, 3]

In [22]:
my_numpy_array1 = np.array(my_list1)

In [23]:
my_numpy_array2 = np.array(my_list2)

In [24]:
my_numpy_array1 + my_numpy_array2

array([3, 5])

In [25]:
# isin icine numpy kodugunu ekledgimiz zaman matematiksel islemleri yapailiyoruz

In [26]:
my_numpy_array1 * my_numpy_array2

array([2, 6])

In [27]:
# anlasilmasi icin art arda 2 tane ornek verelim 

In [28]:
my_numpy_array1 * 5

array([ 5, 10])

In [29]:
my_list1 * 5 

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [31]:
# carpma islemi yaparken satir sutun sayilari ayni olmak zorundadir yoksa kod hata verir

In [32]:
# ARRANGE & INDEX 

In [34]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
np_array = np.arange(0,10)

In [37]:
np_array[0]

np.int64(0)

In [38]:
np_array[-1]

np.int64(9)

In [40]:
np_array[1:4:]

array([1, 2, 3])

In [41]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
np.random.randn(4)

array([ 0.06843047,  0.81355901, -0.77796993,  0.82778436])

In [43]:
np.random.randn(4,4)

array([[ 0.80464529, -0.27322534, -0.93275561, -0.21818798],
       [-0.91709943,  0.14520121, -0.24606024, -0.14911887],
       [ 0.8480639 ,  0.21081137,  1.29377169, -0.11066193],
       [-1.58982065,  0.75633054,  1.12768638, -1.89997102]])

In [44]:
np.random.randint(1,300,5)

array([219,  72, 272, 142,  89], dtype=int32)

In [45]:
# MATRIX

In [46]:
my_matrix = [ [1,2] , [3,4]]

In [47]:
my_matrix

[[1, 2], [3, 4]]

In [49]:
# row + column  

In [51]:
numpy_matrix = np.array([[5,6],[7,8]])

In [52]:
numpy_matrix

array([[5, 6],
       [7, 8]])

In [53]:
numpy_matrix[1][0]

np.int64(7)

In [54]:
numpy_matrix.sum()

np.int64(26)

In [55]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [59]:
np.random.random((3,2))

array([[0.95867704, 0.67806497],
       [0.34718899, 0.12926262],
       [0.25343478, 0.79934071]])

In [60]:
# matrix aritmatik

In [62]:
first_array = np.array([[10,20],[30,40]])

In [66]:
second_array = np.array([[5,15],[25,35]])

In [67]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [68]:
first_array 

array([[10, 20],
       [30, 40]])

In [69]:
third_array = np.array([50,60])

In [70]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [71]:
fourth_array = np.array([10,20,30,40,50])

In [73]:
first_array + fourth_array   kodumuz hata verir cunku matris satir sutun kuralina uymaz

SyntaxError: invalid syntax (3605650821.py, line 1)

In [74]:
fourth_array / 2 

array([ 5., 10., 15., 20., 25.])

In [75]:
five_array = np.array([[10],[4]])

In [76]:
five_array

array([[10],
       [ 4]])

In [78]:
first_array

array([[10, 20],
       [30, 40]])

In [77]:
first_array + five_array

array([[20, 30],
       [34, 44]])

In [79]:
# matrix multiplation

In [80]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [83]:
#  dot product ( bu bir matrix carpimidir)

In [97]:
first_matrix = np.array([10,20,30])

In [98]:
second_matrix = np.array([[2,3],[4,5],[6,7]])

In [99]:
second_matrix

array([[2, 3],
       [4, 5],
       [6, 7]])

In [100]:
second_matrix.shape # matrix ijn bouyutunu bize gosteriyor 

(3, 2)

In [101]:
first_matrix.shape

(3,)

In [103]:
result_matrix = first_matrix.dot(second_matrix)

In [104]:
result_matrix

array([280, 340])

In [105]:
result_matrix.shape

(2,)

In [106]:
# NUMPY ICIN ORNEK COZUMU

In [107]:
new_array = np.random.randint(1,100,20)

In [108]:
new_array

array([63, 16, 86, 50, 90, 86, 74, 79, 43, 23, 87, 25, 32, 70, 61, 34, 28,
       84, 49, 23], dtype=int32)

In [109]:
new_array > 25

array([ True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False])

In [110]:
new_array[new_array > 25]

array([63, 86, 50, 90, 86, 74, 79, 43, 87, 32, 70, 61, 34, 28, 84, 49],
      dtype=int32)

In [111]:
new_array[new_array < 25 ]

array([16, 23, 23], dtype=int32)

In [112]:
# transpoze

In [113]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [114]:
matrix_array.shape

(3, 2)

In [118]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [119]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [121]:
random_array = np.random.random((6,1))

In [124]:
random_array.shape

(6, 1)

In [125]:
random_array.reshape(2,3)

array([[0.5590651 , 0.99738213, 0.19350668],
       [0.47477794, 0.21084096, 0.67398726]])

In [126]:
# z- score

In [127]:
data = np.array([10,12,13,14,15,16,25,100,105])

In [128]:
#outlier

In [129]:
mean = np.mean(data)

In [134]:
mean

np.float64(34.44444444444444)

In [139]:
sum_ = data.sum()

In [140]:
std = data.std()

In [141]:
z_scores = ( data - mean ) / std

In [142]:
z_scores

array([-0.66770982, -0.61307902, -0.58576361, -0.55844821, -0.53113281,
       -0.50381741, -0.25797879,  1.79067634,  1.92725334])

In [143]:
data[z_scores > 1 ]

array([100, 105])

In [144]:
#  2x + 3y = 8 and 5x + 7y =19

In [145]:
#coefficient

In [147]:
A = np.array([[2,3],[5,7]])

In [148]:
#constant

In [149]:
b = np.array([8,19])

In [150]:
solution = np.linalg.solve(A,b)

In [152]:
solution

array([1., 2.])